version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: demo-transactions-container
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: transactions_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
