spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transactions_db?createDatabaseIfNotExist=true
    username: admin
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # or create, create-drop, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
